
services:
  api:
    build: .
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

  redis_database:
    image: "redis:alpine"
    command: redis-server --save 20 1 --loglevel warning --requirepass 1234
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
